name: getx_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.1 <4.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_barcode_scanner: ^2.0.0
  # form_builder_validators: ^9.0.0
  # flutter_form_builder: ^9.0.0
  # get_storage: ^2.1.1
  data_table_2: ^2.5.3
  hexcolor: ^3.0.1
  syncfusion_flutter_datagrid: ^22.1.38
  syncfusion_flutter_core: ^22.1.38
  google_fonts: ^5.1.0
  get_storage: ^2.1.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  connectivity_plus: ^3.0.1
  fl_chart: ^0.60.0
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/google_fonts/

